name: Shodei CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, xml, bcmath, curl

      - name: Install Dependencies
        run: |
          composer install --no-dev --prefer-dist

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.233.143.198  # Your EC2 instance's public IP address
          username: ec2-user     # Your EC2 username
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}  # Reference the private key secret
          script: |
            # Deploying to EC2
            cd /var/www/shodei
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            sudo systemctl restart nginx php8.1-fpm
